sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

env: # a separate build will start for each env
  - TEST_DIR=app

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- cd $TEST_DIR # switch to the directory we're testing
- npm install

script:
- npm run test-ci

after_success:
  - ./node_modules/.bin/codecov # Send coverage