dist: trusty
language: node_js
node_js:
  - '6'

env: # a separate build will start for each env
  - TEST_DIR=app

addons:
  chrome: stable

before_install:
  - cd $TEST_DIR # switch to the directory we're testing
  # npm install happens here

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test-ci

after_success:
  - ./node_modules/.bin/codecov # Send coverage
