# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/insight/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - store_artifacts:
          path: ./test
      - store_test_results:
          path: ./test

  test:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/insight/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run test
      - store_artifacts:
          path: ./test
      - store_test_results:
          path: ./test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

